name: budgeta_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Utilities
  uuid: ^4.5.1
  shared_preferences: ^2.2.3
  flutter_native_splash: ^2.4.1
  flutter_speed_dial: ^7.0.0

  # iOS icons
  cupertino_icons: ^1.0.6

  #firebase
  firebase_auth: ^6.1.2
  firebase_ui_firestore: ^2.0.1
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0

  google_sign_in: ^7.2.0

  # ----------------------------------------
  # ðŸ“Œ ICON PACKAGES
  # ----------------------------------------

  # âœ” Lucide Icons (clean, modern outlines)
  lucide_icons: ^0.257.0

  # âœ” Feather Icons (minimal, thin icons)
  flutter_feather_icons: ^2.0.0

  # âœ” Phosphor Icons (thin, light, boldâ€¦ all styles)
  phosphor_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/app_logo.png
